# MySQL ??

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.8.58/league_of_legends?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: test_user
    password: ENC(WjhVMdlNaZJ1JpuNP5z4x1rAHa8bhZSj)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}